image: mpretet/image_fiche_opj:latest

stages:
    - render

before_script:
    - apt-get update && apt-get install -y libmariadb-dev

render_quarto:
    stage: render
    script:
        - quarto render R/bilan_qubs.qmd
    artifacts:
        paths:
          - /builds/gitlab/vigie-nature/Qubs/bilan_qubs.html