image: mpretet/image_fiche_opj:latest

stages:
    - render

before_script:
    - apt-get update && apt-get install -y libssl-dev libcurl4-gnutls-dev libxml2-dev pandoc

render:
    stage: render
    script:
        - echo "Attention"
        - quarto render R/bilan_qubs.qmd
    artifacts:
        paths:
          - bilan_qubs.html